select * from departments
select * from users
select * from contactgroups
select * from commonmessages
select * from contacts
select * from blacklists
select * from contactgroupmaps;
select * from signatures;
select * from uploadedfiles;
select * from sharedcontactgroups;
select * from sendmessagerules
select * from sendsmsresults
select * from sendmessageresults
select * from resourcereferences
select * from deliveryreports
select * from logitems