// <auto-generated />
namespace EFunTech.Sms.Schema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class v2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2));
        
        string IMigrationMetadata.Id
        {
            get { return "201512131138376_v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
